In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

import torch 

torch.__version__

'1.13.1'

## 00_PyTorch Fundamentals

### Introductions to Tensors

In [2]:
# Creating a Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
# Finding ndim of a tensor (Number of square brackets)
scaler.ndim

0

In [4]:
# Get tensor back as Python int type
# only one element tensors can be converted to Python scalars
scaler.item()

7

In [5]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
# Shape of the tensor
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[1, 2],
                       [3, 10]])
MATRIX

tensor([[ 1,  2],
        [ 3, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([1, 2])

In [12]:
MATRIX[1][1]

tensor(10)

In [13]:
#Tensor
TENSOR = torch.tensor([[[1,2,3,4,5],
                        [1,1,1,1,1]]])
TENSOR

tensor([[[1, 2, 3, 4, 5],
         [1, 1, 1, 1, 1]]])

In [14]:
TENSOR.shape

torch.Size([1, 2, 5])

In [15]:
TENSOR[0]

tensor([[1, 2, 3, 4, 5],
        [1, 1, 1, 1, 1]])

### Random Tensors


In [16]:
# Random tensor of size/shape of 3,4
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1355, 0.2936, 0.7515, 0.4868],
        [0.0916, 0.0557, 0.8730, 0.5867],
        [0.2868, 0.7986, 0.8934, 0.9229]])

In [17]:
# Create a tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels, Height, width
random_image_size_tensor.ndim

3

### Zeros and ones Tensors

In [18]:
#Tensors of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
#Tensors of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Arange Tensors

In [21]:
one_to_nine = torch.arange(0, 10)
one_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
one_to_ten_step_2 = torch.arange(start=0, end=11, step=2)
one_to_ten_step_2

tensor([ 0,  2,  4,  6,  8, 10])

In [23]:
#Create a tensor with the shape of another tensor (Tensor-like)
ten_zeros = torch.zeros_like(input=one_to_ten_step_2)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

### Tensor Datatypes



In [24]:
float_tensor = torch.tensor([3., 6., 9.], 
                            dtype=torch.float16, # Types of float
                            device='cpu', # Where you want the tensor to be stored at
                            requires_grad=False # if you want to track gradients during training
                            )
float_tensor.dtype

torch.float16

In [25]:
print(float_tensor)
print(f"Datatype of Tensor: {float_tensor.dtype}")
print(f"Shape of tensor: {float_tensor.shape}")
print(f"Device tensor is on: {float_tensor.device}")

tensor([3., 6., 9.], dtype=torch.float16)
Datatype of Tensor: torch.float16
Shape of tensor: torch.Size([3])
Device tensor is on: cpu


### Manipulating Tensors (Tensor Operations)


Operation includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [26]:
#Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# element-vise multiplication
tensor * 10

tensor([10, 20, 30])

In [28]:
#Subtraction
tensor - 10

tensor([-9, -8, -7])

In [29]:
# Using pytorch function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [30]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication 

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [31]:
tensor = torch.rand(size=(3, 5))

In [32]:
# Element-wise
tensor * 12

tensor([[11.9318,  7.0319,  3.9485,  2.1821,  1.8203],
        [ 8.0097,  7.1125,  9.0716,  4.6034,  0.1840],
        [10.8939,  7.1922, 10.6095,  1.3289,  4.4172]])

In [33]:
# dot product
torch.matmul(tensor, tensor.T)

# or 
torch.mm(tensor, torch.transpose( tensor, 0, 1 ))

tensor([[1.4964, 1.3318, 1.6208],
        [1.3318, 1.5157, 1.6777],
        [1.6208, 1.6777, 2.1128]])

### Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [34]:
x = torch.arange(0, 101, 10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
torch.min(x), x.min

(tensor(0), <function Tensor.min>)

In [36]:
torch.max(x), x.max

(tensor(100), <function Tensor.max>)

In [37]:
#Mean must be in float
torch.mean( x.type(torch.float16) )

tensor(50., dtype=torch.float16)

In [38]:
torch.sum(x), x.sum()

(tensor(550), tensor(550))

### Reshaping, stacking, squeezing and unqueezing tenors

* Reshaping - Reshapes an input tensor to a defined shape
* View - Returns a view of an input tensor of certain shape but uses the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [39]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [40]:
# Add extra dimension
x_reshaped = x.reshape(-1, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [41]:
# Change the view, it changes the original value
z = x.view(1, 10)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [42]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [43]:
z, z.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [44]:
z.squeeze(), z.squeeze().shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [45]:
torch.unsqueeze(z.squeeze(), dim=1).shape

torch.Size([10, 1])

In [46]:
# permute - rearange the shapes of a tensor
x_original = torch.rand(size=(224, 224, 3))

x_original.permute((2, 0, 1)).shape

torch.Size([3, 224, 224])

### Indexing

Very similar to NumPy arrays

In [47]:
x_original[0, 0, 0] = 999999
x_original[0, 0, 0]

tensor(999999.)

In [48]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [49]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
x[0, 0]
# or x[0][0]

tensor([1, 2, 3])

In [51]:
x[0, 0, 0]

tensor(1)

In [52]:
x[:, 1 , :]

tensor([[4, 5, 6]])

### PyTorch Tensors & NumPy

In [53]:
#Numpy array to tensor

### Numpy default dtype is float64 ###
array = np.arange(1., 8.)

tensor = torch.from_numpy(array).type(torch.float16)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16))

In [54]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), dtype('float32'))

### Reproducibility - Random Numbers

To have a fixed randomness, we need a random seed.

In [55]:
torch.rand(3, 3)

tensor([[0.3043, 0.7102, 0.3414],
        [0.1990, 0.5030, 0.9593],
        [0.9605, 0.6782, 0.6048]])

In [56]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A , random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.3896, 0.1280, 0.6420, 0.6575],
         [0.6080, 0.9599, 0.3671, 0.5875],
         [0.8312, 0.7435, 0.2583, 0.5533]]),
 tensor([[0.8524, 0.8815, 0.8454, 0.0272],
         [0.1494, 0.6707, 0.6121, 0.4918],
         [0.4453, 0.0044, 0.0218, 0.4423]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [57]:
# Setting seed

#Need to set a seed on every random code you use. If you want constant values for all code.
# https://pytorch.org/docs/stable/notes/randomness.html

RANDOM_SEED = 4
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

# torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D, random_tensor_D == random_tensor_C

(tensor([[0.5596, 0.5591, 0.0915, 0.2100],
         [0.0072, 0.0390, 0.9929, 0.9131],
         [0.6186, 0.9744, 0.3189, 0.2148]]),
 tensor([[0.9263, 0.4735, 0.5949, 0.7956],
         [0.7635, 0.2137, 0.3066, 0.0386],
         [0.5220, 0.3207, 0.6074, 0.5233]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

### GPUs

#### Check if GPU exists

In [62]:
torch.cuda.is_available()

True

In [63]:
# Setup device agnoistic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [64]:
#Count number of device
torch.cuda.device_count()

1

#### Using t

#### Running tensors on GPUs

In [65]:
# tensor creation defualt is the cpu
tensor = torch.tensor([1, 2, 3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [66]:
# Putting tensors on the GPU
tensor_on_gpu = tensor.to(device=device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [68]:
# Moving tensors back to the CPU

#If tensor is on GPU, can't transfrom it to NumPy
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])